import Head from 'next/head'
import Sidebar from '@/components/Sidebar'

export default function Home() {
  return (
    <main>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Sidebar/>
    </main>
  )
}
